// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: metrics.proto
#ifndef GRPC_metrics_2eproto__INCLUDED
#define GRPC_metrics_2eproto__INCLUDED

#include "metrics.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace metricsys {

class MetricsService final {
 public:
  static constexpr char const* service_full_name() {
    return "metricsys.MetricsService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetPageViews(::grpc::ClientContext* context, const ::metricsys::GetPageViewsRequest& request, ::metricsys::GetPageViewsResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::metricsys::GetPageViewsResponse>> AsyncGetPageViews(::grpc::ClientContext* context, const ::metricsys::GetPageViewsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::metricsys::GetPageViewsResponse>>(AsyncGetPageViewsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::metricsys::GetPageViewsResponse>> PrepareAsyncGetPageViews(::grpc::ClientContext* context, const ::metricsys::GetPageViewsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::metricsys::GetPageViewsResponse>>(PrepareAsyncGetPageViewsRaw(context, request, cq));
    }
    virtual ::grpc::Status GetClicks(::grpc::ClientContext* context, const ::metricsys::GetClicksRequest& request, ::metricsys::GetClicksResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::metricsys::GetClicksResponse>> AsyncGetClicks(::grpc::ClientContext* context, const ::metricsys::GetClicksRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::metricsys::GetClicksResponse>>(AsyncGetClicksRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::metricsys::GetClicksResponse>> PrepareAsyncGetClicks(::grpc::ClientContext* context, const ::metricsys::GetClicksRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::metricsys::GetClicksResponse>>(PrepareAsyncGetClicksRaw(context, request, cq));
    }
    virtual ::grpc::Status GetPerformance(::grpc::ClientContext* context, const ::metricsys::GetPerformanceRequest& request, ::metricsys::GetPerformanceResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::metricsys::GetPerformanceResponse>> AsyncGetPerformance(::grpc::ClientContext* context, const ::metricsys::GetPerformanceRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::metricsys::GetPerformanceResponse>>(AsyncGetPerformanceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::metricsys::GetPerformanceResponse>> PrepareAsyncGetPerformance(::grpc::ClientContext* context, const ::metricsys::GetPerformanceRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::metricsys::GetPerformanceResponse>>(PrepareAsyncGetPerformanceRaw(context, request, cq));
    }
    virtual ::grpc::Status GetErrors(::grpc::ClientContext* context, const ::metricsys::GetErrorsRequest& request, ::metricsys::GetErrorsResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::metricsys::GetErrorsResponse>> AsyncGetErrors(::grpc::ClientContext* context, const ::metricsys::GetErrorsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::metricsys::GetErrorsResponse>>(AsyncGetErrorsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::metricsys::GetErrorsResponse>> PrepareAsyncGetErrors(::grpc::ClientContext* context, const ::metricsys::GetErrorsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::metricsys::GetErrorsResponse>>(PrepareAsyncGetErrorsRaw(context, request, cq));
    }
    virtual ::grpc::Status GetCustomEvents(::grpc::ClientContext* context, const ::metricsys::GetCustomEventsRequest& request, ::metricsys::GetCustomEventsResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::metricsys::GetCustomEventsResponse>> AsyncGetCustomEvents(::grpc::ClientContext* context, const ::metricsys::GetCustomEventsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::metricsys::GetCustomEventsResponse>>(AsyncGetCustomEventsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::metricsys::GetCustomEventsResponse>> PrepareAsyncGetCustomEvents(::grpc::ClientContext* context, const ::metricsys::GetCustomEventsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::metricsys::GetCustomEventsResponse>>(PrepareAsyncGetCustomEventsRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void GetPageViews(::grpc::ClientContext* context, const ::metricsys::GetPageViewsRequest* request, ::metricsys::GetPageViewsResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetPageViews(::grpc::ClientContext* context, const ::metricsys::GetPageViewsRequest* request, ::metricsys::GetPageViewsResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void GetClicks(::grpc::ClientContext* context, const ::metricsys::GetClicksRequest* request, ::metricsys::GetClicksResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetClicks(::grpc::ClientContext* context, const ::metricsys::GetClicksRequest* request, ::metricsys::GetClicksResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void GetPerformance(::grpc::ClientContext* context, const ::metricsys::GetPerformanceRequest* request, ::metricsys::GetPerformanceResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetPerformance(::grpc::ClientContext* context, const ::metricsys::GetPerformanceRequest* request, ::metricsys::GetPerformanceResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void GetErrors(::grpc::ClientContext* context, const ::metricsys::GetErrorsRequest* request, ::metricsys::GetErrorsResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetErrors(::grpc::ClientContext* context, const ::metricsys::GetErrorsRequest* request, ::metricsys::GetErrorsResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void GetCustomEvents(::grpc::ClientContext* context, const ::metricsys::GetCustomEventsRequest* request, ::metricsys::GetCustomEventsResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetCustomEvents(::grpc::ClientContext* context, const ::metricsys::GetCustomEventsRequest* request, ::metricsys::GetCustomEventsResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::metricsys::GetPageViewsResponse>* AsyncGetPageViewsRaw(::grpc::ClientContext* context, const ::metricsys::GetPageViewsRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::metricsys::GetPageViewsResponse>* PrepareAsyncGetPageViewsRaw(::grpc::ClientContext* context, const ::metricsys::GetPageViewsRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::metricsys::GetClicksResponse>* AsyncGetClicksRaw(::grpc::ClientContext* context, const ::metricsys::GetClicksRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::metricsys::GetClicksResponse>* PrepareAsyncGetClicksRaw(::grpc::ClientContext* context, const ::metricsys::GetClicksRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::metricsys::GetPerformanceResponse>* AsyncGetPerformanceRaw(::grpc::ClientContext* context, const ::metricsys::GetPerformanceRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::metricsys::GetPerformanceResponse>* PrepareAsyncGetPerformanceRaw(::grpc::ClientContext* context, const ::metricsys::GetPerformanceRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::metricsys::GetErrorsResponse>* AsyncGetErrorsRaw(::grpc::ClientContext* context, const ::metricsys::GetErrorsRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::metricsys::GetErrorsResponse>* PrepareAsyncGetErrorsRaw(::grpc::ClientContext* context, const ::metricsys::GetErrorsRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::metricsys::GetCustomEventsResponse>* AsyncGetCustomEventsRaw(::grpc::ClientContext* context, const ::metricsys::GetCustomEventsRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::metricsys::GetCustomEventsResponse>* PrepareAsyncGetCustomEventsRaw(::grpc::ClientContext* context, const ::metricsys::GetCustomEventsRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetPageViews(::grpc::ClientContext* context, const ::metricsys::GetPageViewsRequest& request, ::metricsys::GetPageViewsResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::metricsys::GetPageViewsResponse>> AsyncGetPageViews(::grpc::ClientContext* context, const ::metricsys::GetPageViewsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::metricsys::GetPageViewsResponse>>(AsyncGetPageViewsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::metricsys::GetPageViewsResponse>> PrepareAsyncGetPageViews(::grpc::ClientContext* context, const ::metricsys::GetPageViewsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::metricsys::GetPageViewsResponse>>(PrepareAsyncGetPageViewsRaw(context, request, cq));
    }
    ::grpc::Status GetClicks(::grpc::ClientContext* context, const ::metricsys::GetClicksRequest& request, ::metricsys::GetClicksResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::metricsys::GetClicksResponse>> AsyncGetClicks(::grpc::ClientContext* context, const ::metricsys::GetClicksRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::metricsys::GetClicksResponse>>(AsyncGetClicksRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::metricsys::GetClicksResponse>> PrepareAsyncGetClicks(::grpc::ClientContext* context, const ::metricsys::GetClicksRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::metricsys::GetClicksResponse>>(PrepareAsyncGetClicksRaw(context, request, cq));
    }
    ::grpc::Status GetPerformance(::grpc::ClientContext* context, const ::metricsys::GetPerformanceRequest& request, ::metricsys::GetPerformanceResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::metricsys::GetPerformanceResponse>> AsyncGetPerformance(::grpc::ClientContext* context, const ::metricsys::GetPerformanceRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::metricsys::GetPerformanceResponse>>(AsyncGetPerformanceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::metricsys::GetPerformanceResponse>> PrepareAsyncGetPerformance(::grpc::ClientContext* context, const ::metricsys::GetPerformanceRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::metricsys::GetPerformanceResponse>>(PrepareAsyncGetPerformanceRaw(context, request, cq));
    }
    ::grpc::Status GetErrors(::grpc::ClientContext* context, const ::metricsys::GetErrorsRequest& request, ::metricsys::GetErrorsResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::metricsys::GetErrorsResponse>> AsyncGetErrors(::grpc::ClientContext* context, const ::metricsys::GetErrorsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::metricsys::GetErrorsResponse>>(AsyncGetErrorsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::metricsys::GetErrorsResponse>> PrepareAsyncGetErrors(::grpc::ClientContext* context, const ::metricsys::GetErrorsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::metricsys::GetErrorsResponse>>(PrepareAsyncGetErrorsRaw(context, request, cq));
    }
    ::grpc::Status GetCustomEvents(::grpc::ClientContext* context, const ::metricsys::GetCustomEventsRequest& request, ::metricsys::GetCustomEventsResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::metricsys::GetCustomEventsResponse>> AsyncGetCustomEvents(::grpc::ClientContext* context, const ::metricsys::GetCustomEventsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::metricsys::GetCustomEventsResponse>>(AsyncGetCustomEventsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::metricsys::GetCustomEventsResponse>> PrepareAsyncGetCustomEvents(::grpc::ClientContext* context, const ::metricsys::GetCustomEventsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::metricsys::GetCustomEventsResponse>>(PrepareAsyncGetCustomEventsRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetPageViews(::grpc::ClientContext* context, const ::metricsys::GetPageViewsRequest* request, ::metricsys::GetPageViewsResponse* response, std::function<void(::grpc::Status)>) override;
      void GetPageViews(::grpc::ClientContext* context, const ::metricsys::GetPageViewsRequest* request, ::metricsys::GetPageViewsResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetClicks(::grpc::ClientContext* context, const ::metricsys::GetClicksRequest* request, ::metricsys::GetClicksResponse* response, std::function<void(::grpc::Status)>) override;
      void GetClicks(::grpc::ClientContext* context, const ::metricsys::GetClicksRequest* request, ::metricsys::GetClicksResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetPerformance(::grpc::ClientContext* context, const ::metricsys::GetPerformanceRequest* request, ::metricsys::GetPerformanceResponse* response, std::function<void(::grpc::Status)>) override;
      void GetPerformance(::grpc::ClientContext* context, const ::metricsys::GetPerformanceRequest* request, ::metricsys::GetPerformanceResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetErrors(::grpc::ClientContext* context, const ::metricsys::GetErrorsRequest* request, ::metricsys::GetErrorsResponse* response, std::function<void(::grpc::Status)>) override;
      void GetErrors(::grpc::ClientContext* context, const ::metricsys::GetErrorsRequest* request, ::metricsys::GetErrorsResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetCustomEvents(::grpc::ClientContext* context, const ::metricsys::GetCustomEventsRequest* request, ::metricsys::GetCustomEventsResponse* response, std::function<void(::grpc::Status)>) override;
      void GetCustomEvents(::grpc::ClientContext* context, const ::metricsys::GetCustomEventsRequest* request, ::metricsys::GetCustomEventsResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::metricsys::GetPageViewsResponse>* AsyncGetPageViewsRaw(::grpc::ClientContext* context, const ::metricsys::GetPageViewsRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::metricsys::GetPageViewsResponse>* PrepareAsyncGetPageViewsRaw(::grpc::ClientContext* context, const ::metricsys::GetPageViewsRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::metricsys::GetClicksResponse>* AsyncGetClicksRaw(::grpc::ClientContext* context, const ::metricsys::GetClicksRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::metricsys::GetClicksResponse>* PrepareAsyncGetClicksRaw(::grpc::ClientContext* context, const ::metricsys::GetClicksRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::metricsys::GetPerformanceResponse>* AsyncGetPerformanceRaw(::grpc::ClientContext* context, const ::metricsys::GetPerformanceRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::metricsys::GetPerformanceResponse>* PrepareAsyncGetPerformanceRaw(::grpc::ClientContext* context, const ::metricsys::GetPerformanceRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::metricsys::GetErrorsResponse>* AsyncGetErrorsRaw(::grpc::ClientContext* context, const ::metricsys::GetErrorsRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::metricsys::GetErrorsResponse>* PrepareAsyncGetErrorsRaw(::grpc::ClientContext* context, const ::metricsys::GetErrorsRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::metricsys::GetCustomEventsResponse>* AsyncGetCustomEventsRaw(::grpc::ClientContext* context, const ::metricsys::GetCustomEventsRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::metricsys::GetCustomEventsResponse>* PrepareAsyncGetCustomEventsRaw(::grpc::ClientContext* context, const ::metricsys::GetCustomEventsRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetPageViews_;
    const ::grpc::internal::RpcMethod rpcmethod_GetClicks_;
    const ::grpc::internal::RpcMethod rpcmethod_GetPerformance_;
    const ::grpc::internal::RpcMethod rpcmethod_GetErrors_;
    const ::grpc::internal::RpcMethod rpcmethod_GetCustomEvents_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetPageViews(::grpc::ServerContext* context, const ::metricsys::GetPageViewsRequest* request, ::metricsys::GetPageViewsResponse* response);
    virtual ::grpc::Status GetClicks(::grpc::ServerContext* context, const ::metricsys::GetClicksRequest* request, ::metricsys::GetClicksResponse* response);
    virtual ::grpc::Status GetPerformance(::grpc::ServerContext* context, const ::metricsys::GetPerformanceRequest* request, ::metricsys::GetPerformanceResponse* response);
    virtual ::grpc::Status GetErrors(::grpc::ServerContext* context, const ::metricsys::GetErrorsRequest* request, ::metricsys::GetErrorsResponse* response);
    virtual ::grpc::Status GetCustomEvents(::grpc::ServerContext* context, const ::metricsys::GetCustomEventsRequest* request, ::metricsys::GetCustomEventsResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetPageViews : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetPageViews() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetPageViews() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetPageViews(::grpc::ServerContext* /*context*/, const ::metricsys::GetPageViewsRequest* /*request*/, ::metricsys::GetPageViewsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetPageViews(::grpc::ServerContext* context, ::metricsys::GetPageViewsRequest* request, ::grpc::ServerAsyncResponseWriter< ::metricsys::GetPageViewsResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetClicks : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetClicks() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_GetClicks() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetClicks(::grpc::ServerContext* /*context*/, const ::metricsys::GetClicksRequest* /*request*/, ::metricsys::GetClicksResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetClicks(::grpc::ServerContext* context, ::metricsys::GetClicksRequest* request, ::grpc::ServerAsyncResponseWriter< ::metricsys::GetClicksResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetPerformance : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetPerformance() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_GetPerformance() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetPerformance(::grpc::ServerContext* /*context*/, const ::metricsys::GetPerformanceRequest* /*request*/, ::metricsys::GetPerformanceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetPerformance(::grpc::ServerContext* context, ::metricsys::GetPerformanceRequest* request, ::grpc::ServerAsyncResponseWriter< ::metricsys::GetPerformanceResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetErrors : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetErrors() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_GetErrors() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetErrors(::grpc::ServerContext* /*context*/, const ::metricsys::GetErrorsRequest* /*request*/, ::metricsys::GetErrorsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetErrors(::grpc::ServerContext* context, ::metricsys::GetErrorsRequest* request, ::grpc::ServerAsyncResponseWriter< ::metricsys::GetErrorsResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetCustomEvents : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetCustomEvents() {
      ::grpc::Service::MarkMethodAsync(4);
    }
    ~WithAsyncMethod_GetCustomEvents() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetCustomEvents(::grpc::ServerContext* /*context*/, const ::metricsys::GetCustomEventsRequest* /*request*/, ::metricsys::GetCustomEventsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetCustomEvents(::grpc::ServerContext* context, ::metricsys::GetCustomEventsRequest* request, ::grpc::ServerAsyncResponseWriter< ::metricsys::GetCustomEventsResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetPageViews<WithAsyncMethod_GetClicks<WithAsyncMethod_GetPerformance<WithAsyncMethod_GetErrors<WithAsyncMethod_GetCustomEvents<Service > > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetPageViews : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetPageViews() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::metricsys::GetPageViewsRequest, ::metricsys::GetPageViewsResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::metricsys::GetPageViewsRequest* request, ::metricsys::GetPageViewsResponse* response) { return this->GetPageViews(context, request, response); }));}
    void SetMessageAllocatorFor_GetPageViews(
        ::grpc::MessageAllocator< ::metricsys::GetPageViewsRequest, ::metricsys::GetPageViewsResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::metricsys::GetPageViewsRequest, ::metricsys::GetPageViewsResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetPageViews() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetPageViews(::grpc::ServerContext* /*context*/, const ::metricsys::GetPageViewsRequest* /*request*/, ::metricsys::GetPageViewsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetPageViews(
      ::grpc::CallbackServerContext* /*context*/, const ::metricsys::GetPageViewsRequest* /*request*/, ::metricsys::GetPageViewsResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetClicks : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetClicks() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::metricsys::GetClicksRequest, ::metricsys::GetClicksResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::metricsys::GetClicksRequest* request, ::metricsys::GetClicksResponse* response) { return this->GetClicks(context, request, response); }));}
    void SetMessageAllocatorFor_GetClicks(
        ::grpc::MessageAllocator< ::metricsys::GetClicksRequest, ::metricsys::GetClicksResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::metricsys::GetClicksRequest, ::metricsys::GetClicksResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetClicks() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetClicks(::grpc::ServerContext* /*context*/, const ::metricsys::GetClicksRequest* /*request*/, ::metricsys::GetClicksResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetClicks(
      ::grpc::CallbackServerContext* /*context*/, const ::metricsys::GetClicksRequest* /*request*/, ::metricsys::GetClicksResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetPerformance : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetPerformance() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::metricsys::GetPerformanceRequest, ::metricsys::GetPerformanceResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::metricsys::GetPerformanceRequest* request, ::metricsys::GetPerformanceResponse* response) { return this->GetPerformance(context, request, response); }));}
    void SetMessageAllocatorFor_GetPerformance(
        ::grpc::MessageAllocator< ::metricsys::GetPerformanceRequest, ::metricsys::GetPerformanceResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::metricsys::GetPerformanceRequest, ::metricsys::GetPerformanceResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetPerformance() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetPerformance(::grpc::ServerContext* /*context*/, const ::metricsys::GetPerformanceRequest* /*request*/, ::metricsys::GetPerformanceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetPerformance(
      ::grpc::CallbackServerContext* /*context*/, const ::metricsys::GetPerformanceRequest* /*request*/, ::metricsys::GetPerformanceResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetErrors : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetErrors() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::metricsys::GetErrorsRequest, ::metricsys::GetErrorsResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::metricsys::GetErrorsRequest* request, ::metricsys::GetErrorsResponse* response) { return this->GetErrors(context, request, response); }));}
    void SetMessageAllocatorFor_GetErrors(
        ::grpc::MessageAllocator< ::metricsys::GetErrorsRequest, ::metricsys::GetErrorsResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::metricsys::GetErrorsRequest, ::metricsys::GetErrorsResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetErrors() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetErrors(::grpc::ServerContext* /*context*/, const ::metricsys::GetErrorsRequest* /*request*/, ::metricsys::GetErrorsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetErrors(
      ::grpc::CallbackServerContext* /*context*/, const ::metricsys::GetErrorsRequest* /*request*/, ::metricsys::GetErrorsResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetCustomEvents : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetCustomEvents() {
      ::grpc::Service::MarkMethodCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::metricsys::GetCustomEventsRequest, ::metricsys::GetCustomEventsResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::metricsys::GetCustomEventsRequest* request, ::metricsys::GetCustomEventsResponse* response) { return this->GetCustomEvents(context, request, response); }));}
    void SetMessageAllocatorFor_GetCustomEvents(
        ::grpc::MessageAllocator< ::metricsys::GetCustomEventsRequest, ::metricsys::GetCustomEventsResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(4);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::metricsys::GetCustomEventsRequest, ::metricsys::GetCustomEventsResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetCustomEvents() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetCustomEvents(::grpc::ServerContext* /*context*/, const ::metricsys::GetCustomEventsRequest* /*request*/, ::metricsys::GetCustomEventsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetCustomEvents(
      ::grpc::CallbackServerContext* /*context*/, const ::metricsys::GetCustomEventsRequest* /*request*/, ::metricsys::GetCustomEventsResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetPageViews<WithCallbackMethod_GetClicks<WithCallbackMethod_GetPerformance<WithCallbackMethod_GetErrors<WithCallbackMethod_GetCustomEvents<Service > > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetPageViews : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetPageViews() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetPageViews() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetPageViews(::grpc::ServerContext* /*context*/, const ::metricsys::GetPageViewsRequest* /*request*/, ::metricsys::GetPageViewsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetClicks : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetClicks() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_GetClicks() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetClicks(::grpc::ServerContext* /*context*/, const ::metricsys::GetClicksRequest* /*request*/, ::metricsys::GetClicksResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetPerformance : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetPerformance() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_GetPerformance() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetPerformance(::grpc::ServerContext* /*context*/, const ::metricsys::GetPerformanceRequest* /*request*/, ::metricsys::GetPerformanceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetErrors : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetErrors() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_GetErrors() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetErrors(::grpc::ServerContext* /*context*/, const ::metricsys::GetErrorsRequest* /*request*/, ::metricsys::GetErrorsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetCustomEvents : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetCustomEvents() {
      ::grpc::Service::MarkMethodGeneric(4);
    }
    ~WithGenericMethod_GetCustomEvents() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetCustomEvents(::grpc::ServerContext* /*context*/, const ::metricsys::GetCustomEventsRequest* /*request*/, ::metricsys::GetCustomEventsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetPageViews : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetPageViews() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetPageViews() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetPageViews(::grpc::ServerContext* /*context*/, const ::metricsys::GetPageViewsRequest* /*request*/, ::metricsys::GetPageViewsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetPageViews(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetClicks : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetClicks() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_GetClicks() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetClicks(::grpc::ServerContext* /*context*/, const ::metricsys::GetClicksRequest* /*request*/, ::metricsys::GetClicksResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetClicks(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetPerformance : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetPerformance() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_GetPerformance() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetPerformance(::grpc::ServerContext* /*context*/, const ::metricsys::GetPerformanceRequest* /*request*/, ::metricsys::GetPerformanceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetPerformance(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetErrors : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetErrors() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_GetErrors() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetErrors(::grpc::ServerContext* /*context*/, const ::metricsys::GetErrorsRequest* /*request*/, ::metricsys::GetErrorsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetErrors(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetCustomEvents : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetCustomEvents() {
      ::grpc::Service::MarkMethodRaw(4);
    }
    ~WithRawMethod_GetCustomEvents() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetCustomEvents(::grpc::ServerContext* /*context*/, const ::metricsys::GetCustomEventsRequest* /*request*/, ::metricsys::GetCustomEventsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetCustomEvents(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetPageViews : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetPageViews() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetPageViews(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetPageViews() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetPageViews(::grpc::ServerContext* /*context*/, const ::metricsys::GetPageViewsRequest* /*request*/, ::metricsys::GetPageViewsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetPageViews(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetClicks : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetClicks() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetClicks(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetClicks() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetClicks(::grpc::ServerContext* /*context*/, const ::metricsys::GetClicksRequest* /*request*/, ::metricsys::GetClicksResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetClicks(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetPerformance : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetPerformance() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetPerformance(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetPerformance() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetPerformance(::grpc::ServerContext* /*context*/, const ::metricsys::GetPerformanceRequest* /*request*/, ::metricsys::GetPerformanceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetPerformance(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetErrors : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetErrors() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetErrors(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetErrors() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetErrors(::grpc::ServerContext* /*context*/, const ::metricsys::GetErrorsRequest* /*request*/, ::metricsys::GetErrorsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetErrors(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetCustomEvents : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetCustomEvents() {
      ::grpc::Service::MarkMethodRawCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetCustomEvents(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetCustomEvents() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetCustomEvents(::grpc::ServerContext* /*context*/, const ::metricsys::GetCustomEventsRequest* /*request*/, ::metricsys::GetCustomEventsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetCustomEvents(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetPageViews : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetPageViews() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::metricsys::GetPageViewsRequest, ::metricsys::GetPageViewsResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::metricsys::GetPageViewsRequest, ::metricsys::GetPageViewsResponse>* streamer) {
                       return this->StreamedGetPageViews(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetPageViews() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetPageViews(::grpc::ServerContext* /*context*/, const ::metricsys::GetPageViewsRequest* /*request*/, ::metricsys::GetPageViewsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetPageViews(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::metricsys::GetPageViewsRequest,::metricsys::GetPageViewsResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetClicks : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetClicks() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::metricsys::GetClicksRequest, ::metricsys::GetClicksResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::metricsys::GetClicksRequest, ::metricsys::GetClicksResponse>* streamer) {
                       return this->StreamedGetClicks(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetClicks() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetClicks(::grpc::ServerContext* /*context*/, const ::metricsys::GetClicksRequest* /*request*/, ::metricsys::GetClicksResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetClicks(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::metricsys::GetClicksRequest,::metricsys::GetClicksResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetPerformance : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetPerformance() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::metricsys::GetPerformanceRequest, ::metricsys::GetPerformanceResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::metricsys::GetPerformanceRequest, ::metricsys::GetPerformanceResponse>* streamer) {
                       return this->StreamedGetPerformance(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetPerformance() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetPerformance(::grpc::ServerContext* /*context*/, const ::metricsys::GetPerformanceRequest* /*request*/, ::metricsys::GetPerformanceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetPerformance(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::metricsys::GetPerformanceRequest,::metricsys::GetPerformanceResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetErrors : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetErrors() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::metricsys::GetErrorsRequest, ::metricsys::GetErrorsResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::metricsys::GetErrorsRequest, ::metricsys::GetErrorsResponse>* streamer) {
                       return this->StreamedGetErrors(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetErrors() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetErrors(::grpc::ServerContext* /*context*/, const ::metricsys::GetErrorsRequest* /*request*/, ::metricsys::GetErrorsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetErrors(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::metricsys::GetErrorsRequest,::metricsys::GetErrorsResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetCustomEvents : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetCustomEvents() {
      ::grpc::Service::MarkMethodStreamed(4,
        new ::grpc::internal::StreamedUnaryHandler<
          ::metricsys::GetCustomEventsRequest, ::metricsys::GetCustomEventsResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::metricsys::GetCustomEventsRequest, ::metricsys::GetCustomEventsResponse>* streamer) {
                       return this->StreamedGetCustomEvents(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetCustomEvents() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetCustomEvents(::grpc::ServerContext* /*context*/, const ::metricsys::GetCustomEventsRequest* /*request*/, ::metricsys::GetCustomEventsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetCustomEvents(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::metricsys::GetCustomEventsRequest,::metricsys::GetCustomEventsResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetPageViews<WithStreamedUnaryMethod_GetClicks<WithStreamedUnaryMethod_GetPerformance<WithStreamedUnaryMethod_GetErrors<WithStreamedUnaryMethod_GetCustomEvents<Service > > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetPageViews<WithStreamedUnaryMethod_GetClicks<WithStreamedUnaryMethod_GetPerformance<WithStreamedUnaryMethod_GetErrors<WithStreamedUnaryMethod_GetCustomEvents<Service > > > > > StreamedService;
};

}  // namespace metricsys


#endif  // GRPC_metrics_2eproto__INCLUDED
