// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: aggregation.proto

#include "aggregation.pb.h"
#include "aggregation.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace metricsys {
namespace aggregation {

static const char* AggregationService_method_names[] = {
  "/metricsys.aggregation.AggregationService/GetWatermark",
  "/metricsys.aggregation.AggregationService/GetPageViewsAgg",
  "/metricsys.aggregation.AggregationService/GetClicksAgg",
  "/metricsys.aggregation.AggregationService/GetPerformanceAgg",
  "/metricsys.aggregation.AggregationService/GetErrorsAgg",
  "/metricsys.aggregation.AggregationService/GetCustomEventsAgg",
};

std::unique_ptr< AggregationService::Stub> AggregationService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< AggregationService::Stub> stub(new AggregationService::Stub(channel, options));
  return stub;
}

AggregationService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetWatermark_(AggregationService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetPageViewsAgg_(AggregationService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetClicksAgg_(AggregationService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetPerformanceAgg_(AggregationService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetErrorsAgg_(AggregationService_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetCustomEventsAgg_(AggregationService_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status AggregationService::Stub::GetWatermark(::grpc::ClientContext* context, const ::metricsys::aggregation::GetWatermarkRequest& request, ::metricsys::aggregation::GetWatermarkResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::metricsys::aggregation::GetWatermarkRequest, ::metricsys::aggregation::GetWatermarkResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetWatermark_, context, request, response);
}

void AggregationService::Stub::async::GetWatermark(::grpc::ClientContext* context, const ::metricsys::aggregation::GetWatermarkRequest* request, ::metricsys::aggregation::GetWatermarkResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::metricsys::aggregation::GetWatermarkRequest, ::metricsys::aggregation::GetWatermarkResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetWatermark_, context, request, response, std::move(f));
}

void AggregationService::Stub::async::GetWatermark(::grpc::ClientContext* context, const ::metricsys::aggregation::GetWatermarkRequest* request, ::metricsys::aggregation::GetWatermarkResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetWatermark_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::metricsys::aggregation::GetWatermarkResponse>* AggregationService::Stub::PrepareAsyncGetWatermarkRaw(::grpc::ClientContext* context, const ::metricsys::aggregation::GetWatermarkRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::metricsys::aggregation::GetWatermarkResponse, ::metricsys::aggregation::GetWatermarkRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetWatermark_, context, request);
}

::grpc::ClientAsyncResponseReader< ::metricsys::aggregation::GetWatermarkResponse>* AggregationService::Stub::AsyncGetWatermarkRaw(::grpc::ClientContext* context, const ::metricsys::aggregation::GetWatermarkRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetWatermarkRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AggregationService::Stub::GetPageViewsAgg(::grpc::ClientContext* context, const ::metricsys::aggregation::GetPageViewsAggRequest& request, ::metricsys::aggregation::GetPageViewsAggResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::metricsys::aggregation::GetPageViewsAggRequest, ::metricsys::aggregation::GetPageViewsAggResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetPageViewsAgg_, context, request, response);
}

void AggregationService::Stub::async::GetPageViewsAgg(::grpc::ClientContext* context, const ::metricsys::aggregation::GetPageViewsAggRequest* request, ::metricsys::aggregation::GetPageViewsAggResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::metricsys::aggregation::GetPageViewsAggRequest, ::metricsys::aggregation::GetPageViewsAggResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetPageViewsAgg_, context, request, response, std::move(f));
}

void AggregationService::Stub::async::GetPageViewsAgg(::grpc::ClientContext* context, const ::metricsys::aggregation::GetPageViewsAggRequest* request, ::metricsys::aggregation::GetPageViewsAggResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetPageViewsAgg_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::metricsys::aggregation::GetPageViewsAggResponse>* AggregationService::Stub::PrepareAsyncGetPageViewsAggRaw(::grpc::ClientContext* context, const ::metricsys::aggregation::GetPageViewsAggRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::metricsys::aggregation::GetPageViewsAggResponse, ::metricsys::aggregation::GetPageViewsAggRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetPageViewsAgg_, context, request);
}

::grpc::ClientAsyncResponseReader< ::metricsys::aggregation::GetPageViewsAggResponse>* AggregationService::Stub::AsyncGetPageViewsAggRaw(::grpc::ClientContext* context, const ::metricsys::aggregation::GetPageViewsAggRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetPageViewsAggRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AggregationService::Stub::GetClicksAgg(::grpc::ClientContext* context, const ::metricsys::aggregation::GetClicksAggRequest& request, ::metricsys::aggregation::GetClicksAggResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::metricsys::aggregation::GetClicksAggRequest, ::metricsys::aggregation::GetClicksAggResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetClicksAgg_, context, request, response);
}

void AggregationService::Stub::async::GetClicksAgg(::grpc::ClientContext* context, const ::metricsys::aggregation::GetClicksAggRequest* request, ::metricsys::aggregation::GetClicksAggResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::metricsys::aggregation::GetClicksAggRequest, ::metricsys::aggregation::GetClicksAggResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetClicksAgg_, context, request, response, std::move(f));
}

void AggregationService::Stub::async::GetClicksAgg(::grpc::ClientContext* context, const ::metricsys::aggregation::GetClicksAggRequest* request, ::metricsys::aggregation::GetClicksAggResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetClicksAgg_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::metricsys::aggregation::GetClicksAggResponse>* AggregationService::Stub::PrepareAsyncGetClicksAggRaw(::grpc::ClientContext* context, const ::metricsys::aggregation::GetClicksAggRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::metricsys::aggregation::GetClicksAggResponse, ::metricsys::aggregation::GetClicksAggRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetClicksAgg_, context, request);
}

::grpc::ClientAsyncResponseReader< ::metricsys::aggregation::GetClicksAggResponse>* AggregationService::Stub::AsyncGetClicksAggRaw(::grpc::ClientContext* context, const ::metricsys::aggregation::GetClicksAggRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetClicksAggRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AggregationService::Stub::GetPerformanceAgg(::grpc::ClientContext* context, const ::metricsys::aggregation::GetPerformanceAggRequest& request, ::metricsys::aggregation::GetPerformanceAggResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::metricsys::aggregation::GetPerformanceAggRequest, ::metricsys::aggregation::GetPerformanceAggResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetPerformanceAgg_, context, request, response);
}

void AggregationService::Stub::async::GetPerformanceAgg(::grpc::ClientContext* context, const ::metricsys::aggregation::GetPerformanceAggRequest* request, ::metricsys::aggregation::GetPerformanceAggResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::metricsys::aggregation::GetPerformanceAggRequest, ::metricsys::aggregation::GetPerformanceAggResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetPerformanceAgg_, context, request, response, std::move(f));
}

void AggregationService::Stub::async::GetPerformanceAgg(::grpc::ClientContext* context, const ::metricsys::aggregation::GetPerformanceAggRequest* request, ::metricsys::aggregation::GetPerformanceAggResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetPerformanceAgg_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::metricsys::aggregation::GetPerformanceAggResponse>* AggregationService::Stub::PrepareAsyncGetPerformanceAggRaw(::grpc::ClientContext* context, const ::metricsys::aggregation::GetPerformanceAggRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::metricsys::aggregation::GetPerformanceAggResponse, ::metricsys::aggregation::GetPerformanceAggRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetPerformanceAgg_, context, request);
}

::grpc::ClientAsyncResponseReader< ::metricsys::aggregation::GetPerformanceAggResponse>* AggregationService::Stub::AsyncGetPerformanceAggRaw(::grpc::ClientContext* context, const ::metricsys::aggregation::GetPerformanceAggRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetPerformanceAggRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AggregationService::Stub::GetErrorsAgg(::grpc::ClientContext* context, const ::metricsys::aggregation::GetErrorsAggRequest& request, ::metricsys::aggregation::GetErrorsAggResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::metricsys::aggregation::GetErrorsAggRequest, ::metricsys::aggregation::GetErrorsAggResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetErrorsAgg_, context, request, response);
}

void AggregationService::Stub::async::GetErrorsAgg(::grpc::ClientContext* context, const ::metricsys::aggregation::GetErrorsAggRequest* request, ::metricsys::aggregation::GetErrorsAggResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::metricsys::aggregation::GetErrorsAggRequest, ::metricsys::aggregation::GetErrorsAggResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetErrorsAgg_, context, request, response, std::move(f));
}

void AggregationService::Stub::async::GetErrorsAgg(::grpc::ClientContext* context, const ::metricsys::aggregation::GetErrorsAggRequest* request, ::metricsys::aggregation::GetErrorsAggResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetErrorsAgg_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::metricsys::aggregation::GetErrorsAggResponse>* AggregationService::Stub::PrepareAsyncGetErrorsAggRaw(::grpc::ClientContext* context, const ::metricsys::aggregation::GetErrorsAggRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::metricsys::aggregation::GetErrorsAggResponse, ::metricsys::aggregation::GetErrorsAggRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetErrorsAgg_, context, request);
}

::grpc::ClientAsyncResponseReader< ::metricsys::aggregation::GetErrorsAggResponse>* AggregationService::Stub::AsyncGetErrorsAggRaw(::grpc::ClientContext* context, const ::metricsys::aggregation::GetErrorsAggRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetErrorsAggRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AggregationService::Stub::GetCustomEventsAgg(::grpc::ClientContext* context, const ::metricsys::aggregation::GetCustomEventsAggRequest& request, ::metricsys::aggregation::GetCustomEventsAggResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::metricsys::aggregation::GetCustomEventsAggRequest, ::metricsys::aggregation::GetCustomEventsAggResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetCustomEventsAgg_, context, request, response);
}

void AggregationService::Stub::async::GetCustomEventsAgg(::grpc::ClientContext* context, const ::metricsys::aggregation::GetCustomEventsAggRequest* request, ::metricsys::aggregation::GetCustomEventsAggResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::metricsys::aggregation::GetCustomEventsAggRequest, ::metricsys::aggregation::GetCustomEventsAggResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetCustomEventsAgg_, context, request, response, std::move(f));
}

void AggregationService::Stub::async::GetCustomEventsAgg(::grpc::ClientContext* context, const ::metricsys::aggregation::GetCustomEventsAggRequest* request, ::metricsys::aggregation::GetCustomEventsAggResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetCustomEventsAgg_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::metricsys::aggregation::GetCustomEventsAggResponse>* AggregationService::Stub::PrepareAsyncGetCustomEventsAggRaw(::grpc::ClientContext* context, const ::metricsys::aggregation::GetCustomEventsAggRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::metricsys::aggregation::GetCustomEventsAggResponse, ::metricsys::aggregation::GetCustomEventsAggRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetCustomEventsAgg_, context, request);
}

::grpc::ClientAsyncResponseReader< ::metricsys::aggregation::GetCustomEventsAggResponse>* AggregationService::Stub::AsyncGetCustomEventsAggRaw(::grpc::ClientContext* context, const ::metricsys::aggregation::GetCustomEventsAggRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetCustomEventsAggRaw(context, request, cq);
  result->StartCall();
  return result;
}

AggregationService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AggregationService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AggregationService::Service, ::metricsys::aggregation::GetWatermarkRequest, ::metricsys::aggregation::GetWatermarkResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AggregationService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::metricsys::aggregation::GetWatermarkRequest* req,
             ::metricsys::aggregation::GetWatermarkResponse* resp) {
               return service->GetWatermark(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AggregationService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AggregationService::Service, ::metricsys::aggregation::GetPageViewsAggRequest, ::metricsys::aggregation::GetPageViewsAggResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AggregationService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::metricsys::aggregation::GetPageViewsAggRequest* req,
             ::metricsys::aggregation::GetPageViewsAggResponse* resp) {
               return service->GetPageViewsAgg(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AggregationService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AggregationService::Service, ::metricsys::aggregation::GetClicksAggRequest, ::metricsys::aggregation::GetClicksAggResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AggregationService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::metricsys::aggregation::GetClicksAggRequest* req,
             ::metricsys::aggregation::GetClicksAggResponse* resp) {
               return service->GetClicksAgg(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AggregationService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AggregationService::Service, ::metricsys::aggregation::GetPerformanceAggRequest, ::metricsys::aggregation::GetPerformanceAggResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AggregationService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::metricsys::aggregation::GetPerformanceAggRequest* req,
             ::metricsys::aggregation::GetPerformanceAggResponse* resp) {
               return service->GetPerformanceAgg(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AggregationService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AggregationService::Service, ::metricsys::aggregation::GetErrorsAggRequest, ::metricsys::aggregation::GetErrorsAggResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AggregationService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::metricsys::aggregation::GetErrorsAggRequest* req,
             ::metricsys::aggregation::GetErrorsAggResponse* resp) {
               return service->GetErrorsAgg(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AggregationService_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AggregationService::Service, ::metricsys::aggregation::GetCustomEventsAggRequest, ::metricsys::aggregation::GetCustomEventsAggResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AggregationService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::metricsys::aggregation::GetCustomEventsAggRequest* req,
             ::metricsys::aggregation::GetCustomEventsAggResponse* resp) {
               return service->GetCustomEventsAgg(ctx, req, resp);
             }, this)));
}

AggregationService::Service::~Service() {
}

::grpc::Status AggregationService::Service::GetWatermark(::grpc::ServerContext* context, const ::metricsys::aggregation::GetWatermarkRequest* request, ::metricsys::aggregation::GetWatermarkResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AggregationService::Service::GetPageViewsAgg(::grpc::ServerContext* context, const ::metricsys::aggregation::GetPageViewsAggRequest* request, ::metricsys::aggregation::GetPageViewsAggResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AggregationService::Service::GetClicksAgg(::grpc::ServerContext* context, const ::metricsys::aggregation::GetClicksAggRequest* request, ::metricsys::aggregation::GetClicksAggResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AggregationService::Service::GetPerformanceAgg(::grpc::ServerContext* context, const ::metricsys::aggregation::GetPerformanceAggRequest* request, ::metricsys::aggregation::GetPerformanceAggResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AggregationService::Service::GetErrorsAgg(::grpc::ServerContext* context, const ::metricsys::aggregation::GetErrorsAggRequest* request, ::metricsys::aggregation::GetErrorsAggResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AggregationService::Service::GetCustomEventsAgg(::grpc::ServerContext* context, const ::metricsys::aggregation::GetCustomEventsAggRequest* request, ::metricsys::aggregation::GetCustomEventsAggResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace metricsys
}  // namespace aggregation

