// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: aggregation.proto
#ifndef GRPC_aggregation_2eproto__INCLUDED
#define GRPC_aggregation_2eproto__INCLUDED

#include "aggregation.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace metricsys {
namespace aggregation {

// ===== Service =====
//
class AggregationService final {
 public:
  static constexpr char const* service_full_name() {
    return "metricsys.aggregation.AggregationService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetWatermark(::grpc::ClientContext* context, const ::metricsys::aggregation::GetWatermarkRequest& request, ::metricsys::aggregation::GetWatermarkResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::metricsys::aggregation::GetWatermarkResponse>> AsyncGetWatermark(::grpc::ClientContext* context, const ::metricsys::aggregation::GetWatermarkRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::metricsys::aggregation::GetWatermarkResponse>>(AsyncGetWatermarkRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::metricsys::aggregation::GetWatermarkResponse>> PrepareAsyncGetWatermark(::grpc::ClientContext* context, const ::metricsys::aggregation::GetWatermarkRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::metricsys::aggregation::GetWatermarkResponse>>(PrepareAsyncGetWatermarkRaw(context, request, cq));
    }
    virtual ::grpc::Status GetPageViewsAgg(::grpc::ClientContext* context, const ::metricsys::aggregation::GetPageViewsAggRequest& request, ::metricsys::aggregation::GetPageViewsAggResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::metricsys::aggregation::GetPageViewsAggResponse>> AsyncGetPageViewsAgg(::grpc::ClientContext* context, const ::metricsys::aggregation::GetPageViewsAggRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::metricsys::aggregation::GetPageViewsAggResponse>>(AsyncGetPageViewsAggRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::metricsys::aggregation::GetPageViewsAggResponse>> PrepareAsyncGetPageViewsAgg(::grpc::ClientContext* context, const ::metricsys::aggregation::GetPageViewsAggRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::metricsys::aggregation::GetPageViewsAggResponse>>(PrepareAsyncGetPageViewsAggRaw(context, request, cq));
    }
    virtual ::grpc::Status GetClicksAgg(::grpc::ClientContext* context, const ::metricsys::aggregation::GetClicksAggRequest& request, ::metricsys::aggregation::GetClicksAggResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::metricsys::aggregation::GetClicksAggResponse>> AsyncGetClicksAgg(::grpc::ClientContext* context, const ::metricsys::aggregation::GetClicksAggRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::metricsys::aggregation::GetClicksAggResponse>>(AsyncGetClicksAggRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::metricsys::aggregation::GetClicksAggResponse>> PrepareAsyncGetClicksAgg(::grpc::ClientContext* context, const ::metricsys::aggregation::GetClicksAggRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::metricsys::aggregation::GetClicksAggResponse>>(PrepareAsyncGetClicksAggRaw(context, request, cq));
    }
    virtual ::grpc::Status GetPerformanceAgg(::grpc::ClientContext* context, const ::metricsys::aggregation::GetPerformanceAggRequest& request, ::metricsys::aggregation::GetPerformanceAggResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::metricsys::aggregation::GetPerformanceAggResponse>> AsyncGetPerformanceAgg(::grpc::ClientContext* context, const ::metricsys::aggregation::GetPerformanceAggRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::metricsys::aggregation::GetPerformanceAggResponse>>(AsyncGetPerformanceAggRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::metricsys::aggregation::GetPerformanceAggResponse>> PrepareAsyncGetPerformanceAgg(::grpc::ClientContext* context, const ::metricsys::aggregation::GetPerformanceAggRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::metricsys::aggregation::GetPerformanceAggResponse>>(PrepareAsyncGetPerformanceAggRaw(context, request, cq));
    }
    virtual ::grpc::Status GetErrorsAgg(::grpc::ClientContext* context, const ::metricsys::aggregation::GetErrorsAggRequest& request, ::metricsys::aggregation::GetErrorsAggResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::metricsys::aggregation::GetErrorsAggResponse>> AsyncGetErrorsAgg(::grpc::ClientContext* context, const ::metricsys::aggregation::GetErrorsAggRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::metricsys::aggregation::GetErrorsAggResponse>>(AsyncGetErrorsAggRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::metricsys::aggregation::GetErrorsAggResponse>> PrepareAsyncGetErrorsAgg(::grpc::ClientContext* context, const ::metricsys::aggregation::GetErrorsAggRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::metricsys::aggregation::GetErrorsAggResponse>>(PrepareAsyncGetErrorsAggRaw(context, request, cq));
    }
    virtual ::grpc::Status GetCustomEventsAgg(::grpc::ClientContext* context, const ::metricsys::aggregation::GetCustomEventsAggRequest& request, ::metricsys::aggregation::GetCustomEventsAggResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::metricsys::aggregation::GetCustomEventsAggResponse>> AsyncGetCustomEventsAgg(::grpc::ClientContext* context, const ::metricsys::aggregation::GetCustomEventsAggRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::metricsys::aggregation::GetCustomEventsAggResponse>>(AsyncGetCustomEventsAggRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::metricsys::aggregation::GetCustomEventsAggResponse>> PrepareAsyncGetCustomEventsAgg(::grpc::ClientContext* context, const ::metricsys::aggregation::GetCustomEventsAggRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::metricsys::aggregation::GetCustomEventsAggResponse>>(PrepareAsyncGetCustomEventsAggRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void GetWatermark(::grpc::ClientContext* context, const ::metricsys::aggregation::GetWatermarkRequest* request, ::metricsys::aggregation::GetWatermarkResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetWatermark(::grpc::ClientContext* context, const ::metricsys::aggregation::GetWatermarkRequest* request, ::metricsys::aggregation::GetWatermarkResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void GetPageViewsAgg(::grpc::ClientContext* context, const ::metricsys::aggregation::GetPageViewsAggRequest* request, ::metricsys::aggregation::GetPageViewsAggResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetPageViewsAgg(::grpc::ClientContext* context, const ::metricsys::aggregation::GetPageViewsAggRequest* request, ::metricsys::aggregation::GetPageViewsAggResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void GetClicksAgg(::grpc::ClientContext* context, const ::metricsys::aggregation::GetClicksAggRequest* request, ::metricsys::aggregation::GetClicksAggResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetClicksAgg(::grpc::ClientContext* context, const ::metricsys::aggregation::GetClicksAggRequest* request, ::metricsys::aggregation::GetClicksAggResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void GetPerformanceAgg(::grpc::ClientContext* context, const ::metricsys::aggregation::GetPerformanceAggRequest* request, ::metricsys::aggregation::GetPerformanceAggResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetPerformanceAgg(::grpc::ClientContext* context, const ::metricsys::aggregation::GetPerformanceAggRequest* request, ::metricsys::aggregation::GetPerformanceAggResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void GetErrorsAgg(::grpc::ClientContext* context, const ::metricsys::aggregation::GetErrorsAggRequest* request, ::metricsys::aggregation::GetErrorsAggResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetErrorsAgg(::grpc::ClientContext* context, const ::metricsys::aggregation::GetErrorsAggRequest* request, ::metricsys::aggregation::GetErrorsAggResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void GetCustomEventsAgg(::grpc::ClientContext* context, const ::metricsys::aggregation::GetCustomEventsAggRequest* request, ::metricsys::aggregation::GetCustomEventsAggResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetCustomEventsAgg(::grpc::ClientContext* context, const ::metricsys::aggregation::GetCustomEventsAggRequest* request, ::metricsys::aggregation::GetCustomEventsAggResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::metricsys::aggregation::GetWatermarkResponse>* AsyncGetWatermarkRaw(::grpc::ClientContext* context, const ::metricsys::aggregation::GetWatermarkRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::metricsys::aggregation::GetWatermarkResponse>* PrepareAsyncGetWatermarkRaw(::grpc::ClientContext* context, const ::metricsys::aggregation::GetWatermarkRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::metricsys::aggregation::GetPageViewsAggResponse>* AsyncGetPageViewsAggRaw(::grpc::ClientContext* context, const ::metricsys::aggregation::GetPageViewsAggRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::metricsys::aggregation::GetPageViewsAggResponse>* PrepareAsyncGetPageViewsAggRaw(::grpc::ClientContext* context, const ::metricsys::aggregation::GetPageViewsAggRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::metricsys::aggregation::GetClicksAggResponse>* AsyncGetClicksAggRaw(::grpc::ClientContext* context, const ::metricsys::aggregation::GetClicksAggRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::metricsys::aggregation::GetClicksAggResponse>* PrepareAsyncGetClicksAggRaw(::grpc::ClientContext* context, const ::metricsys::aggregation::GetClicksAggRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::metricsys::aggregation::GetPerformanceAggResponse>* AsyncGetPerformanceAggRaw(::grpc::ClientContext* context, const ::metricsys::aggregation::GetPerformanceAggRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::metricsys::aggregation::GetPerformanceAggResponse>* PrepareAsyncGetPerformanceAggRaw(::grpc::ClientContext* context, const ::metricsys::aggregation::GetPerformanceAggRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::metricsys::aggregation::GetErrorsAggResponse>* AsyncGetErrorsAggRaw(::grpc::ClientContext* context, const ::metricsys::aggregation::GetErrorsAggRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::metricsys::aggregation::GetErrorsAggResponse>* PrepareAsyncGetErrorsAggRaw(::grpc::ClientContext* context, const ::metricsys::aggregation::GetErrorsAggRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::metricsys::aggregation::GetCustomEventsAggResponse>* AsyncGetCustomEventsAggRaw(::grpc::ClientContext* context, const ::metricsys::aggregation::GetCustomEventsAggRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::metricsys::aggregation::GetCustomEventsAggResponse>* PrepareAsyncGetCustomEventsAggRaw(::grpc::ClientContext* context, const ::metricsys::aggregation::GetCustomEventsAggRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetWatermark(::grpc::ClientContext* context, const ::metricsys::aggregation::GetWatermarkRequest& request, ::metricsys::aggregation::GetWatermarkResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::metricsys::aggregation::GetWatermarkResponse>> AsyncGetWatermark(::grpc::ClientContext* context, const ::metricsys::aggregation::GetWatermarkRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::metricsys::aggregation::GetWatermarkResponse>>(AsyncGetWatermarkRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::metricsys::aggregation::GetWatermarkResponse>> PrepareAsyncGetWatermark(::grpc::ClientContext* context, const ::metricsys::aggregation::GetWatermarkRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::metricsys::aggregation::GetWatermarkResponse>>(PrepareAsyncGetWatermarkRaw(context, request, cq));
    }
    ::grpc::Status GetPageViewsAgg(::grpc::ClientContext* context, const ::metricsys::aggregation::GetPageViewsAggRequest& request, ::metricsys::aggregation::GetPageViewsAggResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::metricsys::aggregation::GetPageViewsAggResponse>> AsyncGetPageViewsAgg(::grpc::ClientContext* context, const ::metricsys::aggregation::GetPageViewsAggRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::metricsys::aggregation::GetPageViewsAggResponse>>(AsyncGetPageViewsAggRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::metricsys::aggregation::GetPageViewsAggResponse>> PrepareAsyncGetPageViewsAgg(::grpc::ClientContext* context, const ::metricsys::aggregation::GetPageViewsAggRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::metricsys::aggregation::GetPageViewsAggResponse>>(PrepareAsyncGetPageViewsAggRaw(context, request, cq));
    }
    ::grpc::Status GetClicksAgg(::grpc::ClientContext* context, const ::metricsys::aggregation::GetClicksAggRequest& request, ::metricsys::aggregation::GetClicksAggResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::metricsys::aggregation::GetClicksAggResponse>> AsyncGetClicksAgg(::grpc::ClientContext* context, const ::metricsys::aggregation::GetClicksAggRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::metricsys::aggregation::GetClicksAggResponse>>(AsyncGetClicksAggRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::metricsys::aggregation::GetClicksAggResponse>> PrepareAsyncGetClicksAgg(::grpc::ClientContext* context, const ::metricsys::aggregation::GetClicksAggRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::metricsys::aggregation::GetClicksAggResponse>>(PrepareAsyncGetClicksAggRaw(context, request, cq));
    }
    ::grpc::Status GetPerformanceAgg(::grpc::ClientContext* context, const ::metricsys::aggregation::GetPerformanceAggRequest& request, ::metricsys::aggregation::GetPerformanceAggResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::metricsys::aggregation::GetPerformanceAggResponse>> AsyncGetPerformanceAgg(::grpc::ClientContext* context, const ::metricsys::aggregation::GetPerformanceAggRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::metricsys::aggregation::GetPerformanceAggResponse>>(AsyncGetPerformanceAggRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::metricsys::aggregation::GetPerformanceAggResponse>> PrepareAsyncGetPerformanceAgg(::grpc::ClientContext* context, const ::metricsys::aggregation::GetPerformanceAggRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::metricsys::aggregation::GetPerformanceAggResponse>>(PrepareAsyncGetPerformanceAggRaw(context, request, cq));
    }
    ::grpc::Status GetErrorsAgg(::grpc::ClientContext* context, const ::metricsys::aggregation::GetErrorsAggRequest& request, ::metricsys::aggregation::GetErrorsAggResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::metricsys::aggregation::GetErrorsAggResponse>> AsyncGetErrorsAgg(::grpc::ClientContext* context, const ::metricsys::aggregation::GetErrorsAggRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::metricsys::aggregation::GetErrorsAggResponse>>(AsyncGetErrorsAggRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::metricsys::aggregation::GetErrorsAggResponse>> PrepareAsyncGetErrorsAgg(::grpc::ClientContext* context, const ::metricsys::aggregation::GetErrorsAggRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::metricsys::aggregation::GetErrorsAggResponse>>(PrepareAsyncGetErrorsAggRaw(context, request, cq));
    }
    ::grpc::Status GetCustomEventsAgg(::grpc::ClientContext* context, const ::metricsys::aggregation::GetCustomEventsAggRequest& request, ::metricsys::aggregation::GetCustomEventsAggResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::metricsys::aggregation::GetCustomEventsAggResponse>> AsyncGetCustomEventsAgg(::grpc::ClientContext* context, const ::metricsys::aggregation::GetCustomEventsAggRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::metricsys::aggregation::GetCustomEventsAggResponse>>(AsyncGetCustomEventsAggRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::metricsys::aggregation::GetCustomEventsAggResponse>> PrepareAsyncGetCustomEventsAgg(::grpc::ClientContext* context, const ::metricsys::aggregation::GetCustomEventsAggRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::metricsys::aggregation::GetCustomEventsAggResponse>>(PrepareAsyncGetCustomEventsAggRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetWatermark(::grpc::ClientContext* context, const ::metricsys::aggregation::GetWatermarkRequest* request, ::metricsys::aggregation::GetWatermarkResponse* response, std::function<void(::grpc::Status)>) override;
      void GetWatermark(::grpc::ClientContext* context, const ::metricsys::aggregation::GetWatermarkRequest* request, ::metricsys::aggregation::GetWatermarkResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetPageViewsAgg(::grpc::ClientContext* context, const ::metricsys::aggregation::GetPageViewsAggRequest* request, ::metricsys::aggregation::GetPageViewsAggResponse* response, std::function<void(::grpc::Status)>) override;
      void GetPageViewsAgg(::grpc::ClientContext* context, const ::metricsys::aggregation::GetPageViewsAggRequest* request, ::metricsys::aggregation::GetPageViewsAggResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetClicksAgg(::grpc::ClientContext* context, const ::metricsys::aggregation::GetClicksAggRequest* request, ::metricsys::aggregation::GetClicksAggResponse* response, std::function<void(::grpc::Status)>) override;
      void GetClicksAgg(::grpc::ClientContext* context, const ::metricsys::aggregation::GetClicksAggRequest* request, ::metricsys::aggregation::GetClicksAggResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetPerformanceAgg(::grpc::ClientContext* context, const ::metricsys::aggregation::GetPerformanceAggRequest* request, ::metricsys::aggregation::GetPerformanceAggResponse* response, std::function<void(::grpc::Status)>) override;
      void GetPerformanceAgg(::grpc::ClientContext* context, const ::metricsys::aggregation::GetPerformanceAggRequest* request, ::metricsys::aggregation::GetPerformanceAggResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetErrorsAgg(::grpc::ClientContext* context, const ::metricsys::aggregation::GetErrorsAggRequest* request, ::metricsys::aggregation::GetErrorsAggResponse* response, std::function<void(::grpc::Status)>) override;
      void GetErrorsAgg(::grpc::ClientContext* context, const ::metricsys::aggregation::GetErrorsAggRequest* request, ::metricsys::aggregation::GetErrorsAggResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetCustomEventsAgg(::grpc::ClientContext* context, const ::metricsys::aggregation::GetCustomEventsAggRequest* request, ::metricsys::aggregation::GetCustomEventsAggResponse* response, std::function<void(::grpc::Status)>) override;
      void GetCustomEventsAgg(::grpc::ClientContext* context, const ::metricsys::aggregation::GetCustomEventsAggRequest* request, ::metricsys::aggregation::GetCustomEventsAggResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::metricsys::aggregation::GetWatermarkResponse>* AsyncGetWatermarkRaw(::grpc::ClientContext* context, const ::metricsys::aggregation::GetWatermarkRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::metricsys::aggregation::GetWatermarkResponse>* PrepareAsyncGetWatermarkRaw(::grpc::ClientContext* context, const ::metricsys::aggregation::GetWatermarkRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::metricsys::aggregation::GetPageViewsAggResponse>* AsyncGetPageViewsAggRaw(::grpc::ClientContext* context, const ::metricsys::aggregation::GetPageViewsAggRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::metricsys::aggregation::GetPageViewsAggResponse>* PrepareAsyncGetPageViewsAggRaw(::grpc::ClientContext* context, const ::metricsys::aggregation::GetPageViewsAggRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::metricsys::aggregation::GetClicksAggResponse>* AsyncGetClicksAggRaw(::grpc::ClientContext* context, const ::metricsys::aggregation::GetClicksAggRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::metricsys::aggregation::GetClicksAggResponse>* PrepareAsyncGetClicksAggRaw(::grpc::ClientContext* context, const ::metricsys::aggregation::GetClicksAggRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::metricsys::aggregation::GetPerformanceAggResponse>* AsyncGetPerformanceAggRaw(::grpc::ClientContext* context, const ::metricsys::aggregation::GetPerformanceAggRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::metricsys::aggregation::GetPerformanceAggResponse>* PrepareAsyncGetPerformanceAggRaw(::grpc::ClientContext* context, const ::metricsys::aggregation::GetPerformanceAggRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::metricsys::aggregation::GetErrorsAggResponse>* AsyncGetErrorsAggRaw(::grpc::ClientContext* context, const ::metricsys::aggregation::GetErrorsAggRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::metricsys::aggregation::GetErrorsAggResponse>* PrepareAsyncGetErrorsAggRaw(::grpc::ClientContext* context, const ::metricsys::aggregation::GetErrorsAggRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::metricsys::aggregation::GetCustomEventsAggResponse>* AsyncGetCustomEventsAggRaw(::grpc::ClientContext* context, const ::metricsys::aggregation::GetCustomEventsAggRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::metricsys::aggregation::GetCustomEventsAggResponse>* PrepareAsyncGetCustomEventsAggRaw(::grpc::ClientContext* context, const ::metricsys::aggregation::GetCustomEventsAggRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetWatermark_;
    const ::grpc::internal::RpcMethod rpcmethod_GetPageViewsAgg_;
    const ::grpc::internal::RpcMethod rpcmethod_GetClicksAgg_;
    const ::grpc::internal::RpcMethod rpcmethod_GetPerformanceAgg_;
    const ::grpc::internal::RpcMethod rpcmethod_GetErrorsAgg_;
    const ::grpc::internal::RpcMethod rpcmethod_GetCustomEventsAgg_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetWatermark(::grpc::ServerContext* context, const ::metricsys::aggregation::GetWatermarkRequest* request, ::metricsys::aggregation::GetWatermarkResponse* response);
    virtual ::grpc::Status GetPageViewsAgg(::grpc::ServerContext* context, const ::metricsys::aggregation::GetPageViewsAggRequest* request, ::metricsys::aggregation::GetPageViewsAggResponse* response);
    virtual ::grpc::Status GetClicksAgg(::grpc::ServerContext* context, const ::metricsys::aggregation::GetClicksAggRequest* request, ::metricsys::aggregation::GetClicksAggResponse* response);
    virtual ::grpc::Status GetPerformanceAgg(::grpc::ServerContext* context, const ::metricsys::aggregation::GetPerformanceAggRequest* request, ::metricsys::aggregation::GetPerformanceAggResponse* response);
    virtual ::grpc::Status GetErrorsAgg(::grpc::ServerContext* context, const ::metricsys::aggregation::GetErrorsAggRequest* request, ::metricsys::aggregation::GetErrorsAggResponse* response);
    virtual ::grpc::Status GetCustomEventsAgg(::grpc::ServerContext* context, const ::metricsys::aggregation::GetCustomEventsAggRequest* request, ::metricsys::aggregation::GetCustomEventsAggResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetWatermark : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetWatermark() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetWatermark() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetWatermark(::grpc::ServerContext* /*context*/, const ::metricsys::aggregation::GetWatermarkRequest* /*request*/, ::metricsys::aggregation::GetWatermarkResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetWatermark(::grpc::ServerContext* context, ::metricsys::aggregation::GetWatermarkRequest* request, ::grpc::ServerAsyncResponseWriter< ::metricsys::aggregation::GetWatermarkResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetPageViewsAgg : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetPageViewsAgg() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_GetPageViewsAgg() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetPageViewsAgg(::grpc::ServerContext* /*context*/, const ::metricsys::aggregation::GetPageViewsAggRequest* /*request*/, ::metricsys::aggregation::GetPageViewsAggResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetPageViewsAgg(::grpc::ServerContext* context, ::metricsys::aggregation::GetPageViewsAggRequest* request, ::grpc::ServerAsyncResponseWriter< ::metricsys::aggregation::GetPageViewsAggResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetClicksAgg : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetClicksAgg() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_GetClicksAgg() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetClicksAgg(::grpc::ServerContext* /*context*/, const ::metricsys::aggregation::GetClicksAggRequest* /*request*/, ::metricsys::aggregation::GetClicksAggResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetClicksAgg(::grpc::ServerContext* context, ::metricsys::aggregation::GetClicksAggRequest* request, ::grpc::ServerAsyncResponseWriter< ::metricsys::aggregation::GetClicksAggResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetPerformanceAgg : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetPerformanceAgg() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_GetPerformanceAgg() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetPerformanceAgg(::grpc::ServerContext* /*context*/, const ::metricsys::aggregation::GetPerformanceAggRequest* /*request*/, ::metricsys::aggregation::GetPerformanceAggResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetPerformanceAgg(::grpc::ServerContext* context, ::metricsys::aggregation::GetPerformanceAggRequest* request, ::grpc::ServerAsyncResponseWriter< ::metricsys::aggregation::GetPerformanceAggResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetErrorsAgg : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetErrorsAgg() {
      ::grpc::Service::MarkMethodAsync(4);
    }
    ~WithAsyncMethod_GetErrorsAgg() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetErrorsAgg(::grpc::ServerContext* /*context*/, const ::metricsys::aggregation::GetErrorsAggRequest* /*request*/, ::metricsys::aggregation::GetErrorsAggResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetErrorsAgg(::grpc::ServerContext* context, ::metricsys::aggregation::GetErrorsAggRequest* request, ::grpc::ServerAsyncResponseWriter< ::metricsys::aggregation::GetErrorsAggResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetCustomEventsAgg : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetCustomEventsAgg() {
      ::grpc::Service::MarkMethodAsync(5);
    }
    ~WithAsyncMethod_GetCustomEventsAgg() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetCustomEventsAgg(::grpc::ServerContext* /*context*/, const ::metricsys::aggregation::GetCustomEventsAggRequest* /*request*/, ::metricsys::aggregation::GetCustomEventsAggResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetCustomEventsAgg(::grpc::ServerContext* context, ::metricsys::aggregation::GetCustomEventsAggRequest* request, ::grpc::ServerAsyncResponseWriter< ::metricsys::aggregation::GetCustomEventsAggResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(5, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetWatermark<WithAsyncMethod_GetPageViewsAgg<WithAsyncMethod_GetClicksAgg<WithAsyncMethod_GetPerformanceAgg<WithAsyncMethod_GetErrorsAgg<WithAsyncMethod_GetCustomEventsAgg<Service > > > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetWatermark : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetWatermark() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::metricsys::aggregation::GetWatermarkRequest, ::metricsys::aggregation::GetWatermarkResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::metricsys::aggregation::GetWatermarkRequest* request, ::metricsys::aggregation::GetWatermarkResponse* response) { return this->GetWatermark(context, request, response); }));}
    void SetMessageAllocatorFor_GetWatermark(
        ::grpc::MessageAllocator< ::metricsys::aggregation::GetWatermarkRequest, ::metricsys::aggregation::GetWatermarkResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::metricsys::aggregation::GetWatermarkRequest, ::metricsys::aggregation::GetWatermarkResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetWatermark() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetWatermark(::grpc::ServerContext* /*context*/, const ::metricsys::aggregation::GetWatermarkRequest* /*request*/, ::metricsys::aggregation::GetWatermarkResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetWatermark(
      ::grpc::CallbackServerContext* /*context*/, const ::metricsys::aggregation::GetWatermarkRequest* /*request*/, ::metricsys::aggregation::GetWatermarkResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetPageViewsAgg : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetPageViewsAgg() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::metricsys::aggregation::GetPageViewsAggRequest, ::metricsys::aggregation::GetPageViewsAggResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::metricsys::aggregation::GetPageViewsAggRequest* request, ::metricsys::aggregation::GetPageViewsAggResponse* response) { return this->GetPageViewsAgg(context, request, response); }));}
    void SetMessageAllocatorFor_GetPageViewsAgg(
        ::grpc::MessageAllocator< ::metricsys::aggregation::GetPageViewsAggRequest, ::metricsys::aggregation::GetPageViewsAggResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::metricsys::aggregation::GetPageViewsAggRequest, ::metricsys::aggregation::GetPageViewsAggResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetPageViewsAgg() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetPageViewsAgg(::grpc::ServerContext* /*context*/, const ::metricsys::aggregation::GetPageViewsAggRequest* /*request*/, ::metricsys::aggregation::GetPageViewsAggResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetPageViewsAgg(
      ::grpc::CallbackServerContext* /*context*/, const ::metricsys::aggregation::GetPageViewsAggRequest* /*request*/, ::metricsys::aggregation::GetPageViewsAggResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetClicksAgg : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetClicksAgg() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::metricsys::aggregation::GetClicksAggRequest, ::metricsys::aggregation::GetClicksAggResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::metricsys::aggregation::GetClicksAggRequest* request, ::metricsys::aggregation::GetClicksAggResponse* response) { return this->GetClicksAgg(context, request, response); }));}
    void SetMessageAllocatorFor_GetClicksAgg(
        ::grpc::MessageAllocator< ::metricsys::aggregation::GetClicksAggRequest, ::metricsys::aggregation::GetClicksAggResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::metricsys::aggregation::GetClicksAggRequest, ::metricsys::aggregation::GetClicksAggResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetClicksAgg() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetClicksAgg(::grpc::ServerContext* /*context*/, const ::metricsys::aggregation::GetClicksAggRequest* /*request*/, ::metricsys::aggregation::GetClicksAggResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetClicksAgg(
      ::grpc::CallbackServerContext* /*context*/, const ::metricsys::aggregation::GetClicksAggRequest* /*request*/, ::metricsys::aggregation::GetClicksAggResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetPerformanceAgg : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetPerformanceAgg() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::metricsys::aggregation::GetPerformanceAggRequest, ::metricsys::aggregation::GetPerformanceAggResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::metricsys::aggregation::GetPerformanceAggRequest* request, ::metricsys::aggregation::GetPerformanceAggResponse* response) { return this->GetPerformanceAgg(context, request, response); }));}
    void SetMessageAllocatorFor_GetPerformanceAgg(
        ::grpc::MessageAllocator< ::metricsys::aggregation::GetPerformanceAggRequest, ::metricsys::aggregation::GetPerformanceAggResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::metricsys::aggregation::GetPerformanceAggRequest, ::metricsys::aggregation::GetPerformanceAggResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetPerformanceAgg() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetPerformanceAgg(::grpc::ServerContext* /*context*/, const ::metricsys::aggregation::GetPerformanceAggRequest* /*request*/, ::metricsys::aggregation::GetPerformanceAggResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetPerformanceAgg(
      ::grpc::CallbackServerContext* /*context*/, const ::metricsys::aggregation::GetPerformanceAggRequest* /*request*/, ::metricsys::aggregation::GetPerformanceAggResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetErrorsAgg : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetErrorsAgg() {
      ::grpc::Service::MarkMethodCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::metricsys::aggregation::GetErrorsAggRequest, ::metricsys::aggregation::GetErrorsAggResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::metricsys::aggregation::GetErrorsAggRequest* request, ::metricsys::aggregation::GetErrorsAggResponse* response) { return this->GetErrorsAgg(context, request, response); }));}
    void SetMessageAllocatorFor_GetErrorsAgg(
        ::grpc::MessageAllocator< ::metricsys::aggregation::GetErrorsAggRequest, ::metricsys::aggregation::GetErrorsAggResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(4);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::metricsys::aggregation::GetErrorsAggRequest, ::metricsys::aggregation::GetErrorsAggResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetErrorsAgg() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetErrorsAgg(::grpc::ServerContext* /*context*/, const ::metricsys::aggregation::GetErrorsAggRequest* /*request*/, ::metricsys::aggregation::GetErrorsAggResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetErrorsAgg(
      ::grpc::CallbackServerContext* /*context*/, const ::metricsys::aggregation::GetErrorsAggRequest* /*request*/, ::metricsys::aggregation::GetErrorsAggResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetCustomEventsAgg : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetCustomEventsAgg() {
      ::grpc::Service::MarkMethodCallback(5,
          new ::grpc::internal::CallbackUnaryHandler< ::metricsys::aggregation::GetCustomEventsAggRequest, ::metricsys::aggregation::GetCustomEventsAggResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::metricsys::aggregation::GetCustomEventsAggRequest* request, ::metricsys::aggregation::GetCustomEventsAggResponse* response) { return this->GetCustomEventsAgg(context, request, response); }));}
    void SetMessageAllocatorFor_GetCustomEventsAgg(
        ::grpc::MessageAllocator< ::metricsys::aggregation::GetCustomEventsAggRequest, ::metricsys::aggregation::GetCustomEventsAggResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(5);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::metricsys::aggregation::GetCustomEventsAggRequest, ::metricsys::aggregation::GetCustomEventsAggResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetCustomEventsAgg() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetCustomEventsAgg(::grpc::ServerContext* /*context*/, const ::metricsys::aggregation::GetCustomEventsAggRequest* /*request*/, ::metricsys::aggregation::GetCustomEventsAggResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetCustomEventsAgg(
      ::grpc::CallbackServerContext* /*context*/, const ::metricsys::aggregation::GetCustomEventsAggRequest* /*request*/, ::metricsys::aggregation::GetCustomEventsAggResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetWatermark<WithCallbackMethod_GetPageViewsAgg<WithCallbackMethod_GetClicksAgg<WithCallbackMethod_GetPerformanceAgg<WithCallbackMethod_GetErrorsAgg<WithCallbackMethod_GetCustomEventsAgg<Service > > > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetWatermark : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetWatermark() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetWatermark() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetWatermark(::grpc::ServerContext* /*context*/, const ::metricsys::aggregation::GetWatermarkRequest* /*request*/, ::metricsys::aggregation::GetWatermarkResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetPageViewsAgg : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetPageViewsAgg() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_GetPageViewsAgg() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetPageViewsAgg(::grpc::ServerContext* /*context*/, const ::metricsys::aggregation::GetPageViewsAggRequest* /*request*/, ::metricsys::aggregation::GetPageViewsAggResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetClicksAgg : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetClicksAgg() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_GetClicksAgg() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetClicksAgg(::grpc::ServerContext* /*context*/, const ::metricsys::aggregation::GetClicksAggRequest* /*request*/, ::metricsys::aggregation::GetClicksAggResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetPerformanceAgg : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetPerformanceAgg() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_GetPerformanceAgg() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetPerformanceAgg(::grpc::ServerContext* /*context*/, const ::metricsys::aggregation::GetPerformanceAggRequest* /*request*/, ::metricsys::aggregation::GetPerformanceAggResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetErrorsAgg : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetErrorsAgg() {
      ::grpc::Service::MarkMethodGeneric(4);
    }
    ~WithGenericMethod_GetErrorsAgg() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetErrorsAgg(::grpc::ServerContext* /*context*/, const ::metricsys::aggregation::GetErrorsAggRequest* /*request*/, ::metricsys::aggregation::GetErrorsAggResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetCustomEventsAgg : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetCustomEventsAgg() {
      ::grpc::Service::MarkMethodGeneric(5);
    }
    ~WithGenericMethod_GetCustomEventsAgg() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetCustomEventsAgg(::grpc::ServerContext* /*context*/, const ::metricsys::aggregation::GetCustomEventsAggRequest* /*request*/, ::metricsys::aggregation::GetCustomEventsAggResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetWatermark : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetWatermark() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetWatermark() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetWatermark(::grpc::ServerContext* /*context*/, const ::metricsys::aggregation::GetWatermarkRequest* /*request*/, ::metricsys::aggregation::GetWatermarkResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetWatermark(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetPageViewsAgg : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetPageViewsAgg() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_GetPageViewsAgg() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetPageViewsAgg(::grpc::ServerContext* /*context*/, const ::metricsys::aggregation::GetPageViewsAggRequest* /*request*/, ::metricsys::aggregation::GetPageViewsAggResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetPageViewsAgg(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetClicksAgg : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetClicksAgg() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_GetClicksAgg() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetClicksAgg(::grpc::ServerContext* /*context*/, const ::metricsys::aggregation::GetClicksAggRequest* /*request*/, ::metricsys::aggregation::GetClicksAggResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetClicksAgg(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetPerformanceAgg : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetPerformanceAgg() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_GetPerformanceAgg() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetPerformanceAgg(::grpc::ServerContext* /*context*/, const ::metricsys::aggregation::GetPerformanceAggRequest* /*request*/, ::metricsys::aggregation::GetPerformanceAggResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetPerformanceAgg(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetErrorsAgg : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetErrorsAgg() {
      ::grpc::Service::MarkMethodRaw(4);
    }
    ~WithRawMethod_GetErrorsAgg() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetErrorsAgg(::grpc::ServerContext* /*context*/, const ::metricsys::aggregation::GetErrorsAggRequest* /*request*/, ::metricsys::aggregation::GetErrorsAggResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetErrorsAgg(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetCustomEventsAgg : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetCustomEventsAgg() {
      ::grpc::Service::MarkMethodRaw(5);
    }
    ~WithRawMethod_GetCustomEventsAgg() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetCustomEventsAgg(::grpc::ServerContext* /*context*/, const ::metricsys::aggregation::GetCustomEventsAggRequest* /*request*/, ::metricsys::aggregation::GetCustomEventsAggResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetCustomEventsAgg(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(5, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetWatermark : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetWatermark() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetWatermark(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetWatermark() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetWatermark(::grpc::ServerContext* /*context*/, const ::metricsys::aggregation::GetWatermarkRequest* /*request*/, ::metricsys::aggregation::GetWatermarkResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetWatermark(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetPageViewsAgg : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetPageViewsAgg() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetPageViewsAgg(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetPageViewsAgg() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetPageViewsAgg(::grpc::ServerContext* /*context*/, const ::metricsys::aggregation::GetPageViewsAggRequest* /*request*/, ::metricsys::aggregation::GetPageViewsAggResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetPageViewsAgg(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetClicksAgg : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetClicksAgg() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetClicksAgg(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetClicksAgg() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetClicksAgg(::grpc::ServerContext* /*context*/, const ::metricsys::aggregation::GetClicksAggRequest* /*request*/, ::metricsys::aggregation::GetClicksAggResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetClicksAgg(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetPerformanceAgg : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetPerformanceAgg() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetPerformanceAgg(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetPerformanceAgg() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetPerformanceAgg(::grpc::ServerContext* /*context*/, const ::metricsys::aggregation::GetPerformanceAggRequest* /*request*/, ::metricsys::aggregation::GetPerformanceAggResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetPerformanceAgg(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetErrorsAgg : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetErrorsAgg() {
      ::grpc::Service::MarkMethodRawCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetErrorsAgg(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetErrorsAgg() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetErrorsAgg(::grpc::ServerContext* /*context*/, const ::metricsys::aggregation::GetErrorsAggRequest* /*request*/, ::metricsys::aggregation::GetErrorsAggResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetErrorsAgg(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetCustomEventsAgg : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetCustomEventsAgg() {
      ::grpc::Service::MarkMethodRawCallback(5,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetCustomEventsAgg(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetCustomEventsAgg() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetCustomEventsAgg(::grpc::ServerContext* /*context*/, const ::metricsys::aggregation::GetCustomEventsAggRequest* /*request*/, ::metricsys::aggregation::GetCustomEventsAggResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetCustomEventsAgg(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetWatermark : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetWatermark() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::metricsys::aggregation::GetWatermarkRequest, ::metricsys::aggregation::GetWatermarkResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::metricsys::aggregation::GetWatermarkRequest, ::metricsys::aggregation::GetWatermarkResponse>* streamer) {
                       return this->StreamedGetWatermark(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetWatermark() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetWatermark(::grpc::ServerContext* /*context*/, const ::metricsys::aggregation::GetWatermarkRequest* /*request*/, ::metricsys::aggregation::GetWatermarkResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetWatermark(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::metricsys::aggregation::GetWatermarkRequest,::metricsys::aggregation::GetWatermarkResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetPageViewsAgg : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetPageViewsAgg() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::metricsys::aggregation::GetPageViewsAggRequest, ::metricsys::aggregation::GetPageViewsAggResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::metricsys::aggregation::GetPageViewsAggRequest, ::metricsys::aggregation::GetPageViewsAggResponse>* streamer) {
                       return this->StreamedGetPageViewsAgg(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetPageViewsAgg() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetPageViewsAgg(::grpc::ServerContext* /*context*/, const ::metricsys::aggregation::GetPageViewsAggRequest* /*request*/, ::metricsys::aggregation::GetPageViewsAggResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetPageViewsAgg(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::metricsys::aggregation::GetPageViewsAggRequest,::metricsys::aggregation::GetPageViewsAggResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetClicksAgg : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetClicksAgg() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::metricsys::aggregation::GetClicksAggRequest, ::metricsys::aggregation::GetClicksAggResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::metricsys::aggregation::GetClicksAggRequest, ::metricsys::aggregation::GetClicksAggResponse>* streamer) {
                       return this->StreamedGetClicksAgg(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetClicksAgg() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetClicksAgg(::grpc::ServerContext* /*context*/, const ::metricsys::aggregation::GetClicksAggRequest* /*request*/, ::metricsys::aggregation::GetClicksAggResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetClicksAgg(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::metricsys::aggregation::GetClicksAggRequest,::metricsys::aggregation::GetClicksAggResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetPerformanceAgg : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetPerformanceAgg() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::metricsys::aggregation::GetPerformanceAggRequest, ::metricsys::aggregation::GetPerformanceAggResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::metricsys::aggregation::GetPerformanceAggRequest, ::metricsys::aggregation::GetPerformanceAggResponse>* streamer) {
                       return this->StreamedGetPerformanceAgg(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetPerformanceAgg() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetPerformanceAgg(::grpc::ServerContext* /*context*/, const ::metricsys::aggregation::GetPerformanceAggRequest* /*request*/, ::metricsys::aggregation::GetPerformanceAggResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetPerformanceAgg(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::metricsys::aggregation::GetPerformanceAggRequest,::metricsys::aggregation::GetPerformanceAggResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetErrorsAgg : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetErrorsAgg() {
      ::grpc::Service::MarkMethodStreamed(4,
        new ::grpc::internal::StreamedUnaryHandler<
          ::metricsys::aggregation::GetErrorsAggRequest, ::metricsys::aggregation::GetErrorsAggResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::metricsys::aggregation::GetErrorsAggRequest, ::metricsys::aggregation::GetErrorsAggResponse>* streamer) {
                       return this->StreamedGetErrorsAgg(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetErrorsAgg() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetErrorsAgg(::grpc::ServerContext* /*context*/, const ::metricsys::aggregation::GetErrorsAggRequest* /*request*/, ::metricsys::aggregation::GetErrorsAggResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetErrorsAgg(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::metricsys::aggregation::GetErrorsAggRequest,::metricsys::aggregation::GetErrorsAggResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetCustomEventsAgg : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetCustomEventsAgg() {
      ::grpc::Service::MarkMethodStreamed(5,
        new ::grpc::internal::StreamedUnaryHandler<
          ::metricsys::aggregation::GetCustomEventsAggRequest, ::metricsys::aggregation::GetCustomEventsAggResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::metricsys::aggregation::GetCustomEventsAggRequest, ::metricsys::aggregation::GetCustomEventsAggResponse>* streamer) {
                       return this->StreamedGetCustomEventsAgg(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetCustomEventsAgg() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetCustomEventsAgg(::grpc::ServerContext* /*context*/, const ::metricsys::aggregation::GetCustomEventsAggRequest* /*request*/, ::metricsys::aggregation::GetCustomEventsAggResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetCustomEventsAgg(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::metricsys::aggregation::GetCustomEventsAggRequest,::metricsys::aggregation::GetCustomEventsAggResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetWatermark<WithStreamedUnaryMethod_GetPageViewsAgg<WithStreamedUnaryMethod_GetClicksAgg<WithStreamedUnaryMethod_GetPerformanceAgg<WithStreamedUnaryMethod_GetErrorsAgg<WithStreamedUnaryMethod_GetCustomEventsAgg<Service > > > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetWatermark<WithStreamedUnaryMethod_GetPageViewsAgg<WithStreamedUnaryMethod_GetClicksAgg<WithStreamedUnaryMethod_GetPerformanceAgg<WithStreamedUnaryMethod_GetErrorsAgg<WithStreamedUnaryMethod_GetCustomEventsAgg<Service > > > > > > StreamedService;
};

}  // namespace aggregation
}  // namespace metricsys


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_aggregation_2eproto__INCLUDED
