// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: metrics.proto

#include "metrics.pb.h"
#include "metrics.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace metricsys {

static const char* MetricsService_method_names[] = {
  "/metricsys.MetricsService/GetPageViews",
  "/metricsys.MetricsService/GetClicks",
  "/metricsys.MetricsService/GetPerformance",
  "/metricsys.MetricsService/GetErrors",
  "/metricsys.MetricsService/GetCustomEvents",
};

std::unique_ptr< MetricsService::Stub> MetricsService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< MetricsService::Stub> stub(new MetricsService::Stub(channel, options));
  return stub;
}

MetricsService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetPageViews_(MetricsService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetClicks_(MetricsService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetPerformance_(MetricsService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetErrors_(MetricsService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetCustomEvents_(MetricsService_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status MetricsService::Stub::GetPageViews(::grpc::ClientContext* context, const ::metricsys::GetPageViewsRequest& request, ::metricsys::GetPageViewsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::metricsys::GetPageViewsRequest, ::metricsys::GetPageViewsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetPageViews_, context, request, response);
}

void MetricsService::Stub::async::GetPageViews(::grpc::ClientContext* context, const ::metricsys::GetPageViewsRequest* request, ::metricsys::GetPageViewsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::metricsys::GetPageViewsRequest, ::metricsys::GetPageViewsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetPageViews_, context, request, response, std::move(f));
}

void MetricsService::Stub::async::GetPageViews(::grpc::ClientContext* context, const ::metricsys::GetPageViewsRequest* request, ::metricsys::GetPageViewsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetPageViews_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::metricsys::GetPageViewsResponse>* MetricsService::Stub::PrepareAsyncGetPageViewsRaw(::grpc::ClientContext* context, const ::metricsys::GetPageViewsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::metricsys::GetPageViewsResponse, ::metricsys::GetPageViewsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetPageViews_, context, request);
}

::grpc::ClientAsyncResponseReader< ::metricsys::GetPageViewsResponse>* MetricsService::Stub::AsyncGetPageViewsRaw(::grpc::ClientContext* context, const ::metricsys::GetPageViewsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetPageViewsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status MetricsService::Stub::GetClicks(::grpc::ClientContext* context, const ::metricsys::GetClicksRequest& request, ::metricsys::GetClicksResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::metricsys::GetClicksRequest, ::metricsys::GetClicksResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetClicks_, context, request, response);
}

void MetricsService::Stub::async::GetClicks(::grpc::ClientContext* context, const ::metricsys::GetClicksRequest* request, ::metricsys::GetClicksResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::metricsys::GetClicksRequest, ::metricsys::GetClicksResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetClicks_, context, request, response, std::move(f));
}

void MetricsService::Stub::async::GetClicks(::grpc::ClientContext* context, const ::metricsys::GetClicksRequest* request, ::metricsys::GetClicksResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetClicks_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::metricsys::GetClicksResponse>* MetricsService::Stub::PrepareAsyncGetClicksRaw(::grpc::ClientContext* context, const ::metricsys::GetClicksRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::metricsys::GetClicksResponse, ::metricsys::GetClicksRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetClicks_, context, request);
}

::grpc::ClientAsyncResponseReader< ::metricsys::GetClicksResponse>* MetricsService::Stub::AsyncGetClicksRaw(::grpc::ClientContext* context, const ::metricsys::GetClicksRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetClicksRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status MetricsService::Stub::GetPerformance(::grpc::ClientContext* context, const ::metricsys::GetPerformanceRequest& request, ::metricsys::GetPerformanceResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::metricsys::GetPerformanceRequest, ::metricsys::GetPerformanceResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetPerformance_, context, request, response);
}

void MetricsService::Stub::async::GetPerformance(::grpc::ClientContext* context, const ::metricsys::GetPerformanceRequest* request, ::metricsys::GetPerformanceResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::metricsys::GetPerformanceRequest, ::metricsys::GetPerformanceResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetPerformance_, context, request, response, std::move(f));
}

void MetricsService::Stub::async::GetPerformance(::grpc::ClientContext* context, const ::metricsys::GetPerformanceRequest* request, ::metricsys::GetPerformanceResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetPerformance_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::metricsys::GetPerformanceResponse>* MetricsService::Stub::PrepareAsyncGetPerformanceRaw(::grpc::ClientContext* context, const ::metricsys::GetPerformanceRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::metricsys::GetPerformanceResponse, ::metricsys::GetPerformanceRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetPerformance_, context, request);
}

::grpc::ClientAsyncResponseReader< ::metricsys::GetPerformanceResponse>* MetricsService::Stub::AsyncGetPerformanceRaw(::grpc::ClientContext* context, const ::metricsys::GetPerformanceRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetPerformanceRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status MetricsService::Stub::GetErrors(::grpc::ClientContext* context, const ::metricsys::GetErrorsRequest& request, ::metricsys::GetErrorsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::metricsys::GetErrorsRequest, ::metricsys::GetErrorsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetErrors_, context, request, response);
}

void MetricsService::Stub::async::GetErrors(::grpc::ClientContext* context, const ::metricsys::GetErrorsRequest* request, ::metricsys::GetErrorsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::metricsys::GetErrorsRequest, ::metricsys::GetErrorsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetErrors_, context, request, response, std::move(f));
}

void MetricsService::Stub::async::GetErrors(::grpc::ClientContext* context, const ::metricsys::GetErrorsRequest* request, ::metricsys::GetErrorsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetErrors_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::metricsys::GetErrorsResponse>* MetricsService::Stub::PrepareAsyncGetErrorsRaw(::grpc::ClientContext* context, const ::metricsys::GetErrorsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::metricsys::GetErrorsResponse, ::metricsys::GetErrorsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetErrors_, context, request);
}

::grpc::ClientAsyncResponseReader< ::metricsys::GetErrorsResponse>* MetricsService::Stub::AsyncGetErrorsRaw(::grpc::ClientContext* context, const ::metricsys::GetErrorsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetErrorsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status MetricsService::Stub::GetCustomEvents(::grpc::ClientContext* context, const ::metricsys::GetCustomEventsRequest& request, ::metricsys::GetCustomEventsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::metricsys::GetCustomEventsRequest, ::metricsys::GetCustomEventsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetCustomEvents_, context, request, response);
}

void MetricsService::Stub::async::GetCustomEvents(::grpc::ClientContext* context, const ::metricsys::GetCustomEventsRequest* request, ::metricsys::GetCustomEventsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::metricsys::GetCustomEventsRequest, ::metricsys::GetCustomEventsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetCustomEvents_, context, request, response, std::move(f));
}

void MetricsService::Stub::async::GetCustomEvents(::grpc::ClientContext* context, const ::metricsys::GetCustomEventsRequest* request, ::metricsys::GetCustomEventsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetCustomEvents_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::metricsys::GetCustomEventsResponse>* MetricsService::Stub::PrepareAsyncGetCustomEventsRaw(::grpc::ClientContext* context, const ::metricsys::GetCustomEventsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::metricsys::GetCustomEventsResponse, ::metricsys::GetCustomEventsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetCustomEvents_, context, request);
}

::grpc::ClientAsyncResponseReader< ::metricsys::GetCustomEventsResponse>* MetricsService::Stub::AsyncGetCustomEventsRaw(::grpc::ClientContext* context, const ::metricsys::GetCustomEventsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetCustomEventsRaw(context, request, cq);
  result->StartCall();
  return result;
}

MetricsService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MetricsService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MetricsService::Service, ::metricsys::GetPageViewsRequest, ::metricsys::GetPageViewsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MetricsService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::metricsys::GetPageViewsRequest* req,
             ::metricsys::GetPageViewsResponse* resp) {
               return service->GetPageViews(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MetricsService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MetricsService::Service, ::metricsys::GetClicksRequest, ::metricsys::GetClicksResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MetricsService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::metricsys::GetClicksRequest* req,
             ::metricsys::GetClicksResponse* resp) {
               return service->GetClicks(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MetricsService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MetricsService::Service, ::metricsys::GetPerformanceRequest, ::metricsys::GetPerformanceResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MetricsService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::metricsys::GetPerformanceRequest* req,
             ::metricsys::GetPerformanceResponse* resp) {
               return service->GetPerformance(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MetricsService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MetricsService::Service, ::metricsys::GetErrorsRequest, ::metricsys::GetErrorsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MetricsService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::metricsys::GetErrorsRequest* req,
             ::metricsys::GetErrorsResponse* resp) {
               return service->GetErrors(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MetricsService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MetricsService::Service, ::metricsys::GetCustomEventsRequest, ::metricsys::GetCustomEventsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MetricsService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::metricsys::GetCustomEventsRequest* req,
             ::metricsys::GetCustomEventsResponse* resp) {
               return service->GetCustomEvents(ctx, req, resp);
             }, this)));
}

MetricsService::Service::~Service() {
}

::grpc::Status MetricsService::Service::GetPageViews(::grpc::ServerContext* context, const ::metricsys::GetPageViewsRequest* request, ::metricsys::GetPageViewsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MetricsService::Service::GetClicks(::grpc::ServerContext* context, const ::metricsys::GetClicksRequest* request, ::metricsys::GetClicksResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MetricsService::Service::GetPerformance(::grpc::ServerContext* context, const ::metricsys::GetPerformanceRequest* request, ::metricsys::GetPerformanceResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MetricsService::Service::GetErrors(::grpc::ServerContext* context, const ::metricsys::GetErrorsRequest* request, ::metricsys::GetErrorsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MetricsService::Service::GetCustomEvents(::grpc::ServerContext* context, const ::metricsys::GetCustomEventsRequest* request, ::metricsys::GetCustomEventsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace metricsys

